services:
  db:
    image: mysql:9.4.0
    restart: always
    environment:
      MYSQL_DATABASE: 'cinema_db'
      MYSQL_ROOT_PASSWORD: '53cret'
      MYSQL_USER: 'yuji'
      MYSQL_PASSWORD: '53cret'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
